description: unified_gen_dis

target:
  service: sing
  name: amdmi100vc


environment:
  image: amlt-sing/pytorch-1.11.0-rocm5.1.3 #zeliu98/pytorch:pytorch1.8.1-py38-cuda11.3-cudnn820-openmpi-mmcv-apex-timm # #zeliu98/pytorch:pytorch1.7.1-py37-cuda10.2-cudnn8-openmpi-mmcv-apex-timm  #amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel  #
  # registry: docker.io # any public registry can be specified here
  setup:
    - pip install pytest transformers --user
    - pip install einops fvcore --user
    - pip install --upgrade numpy --user
    - pip install tensorboardX --user
    - pip install timm --user
    - pip install torchmetrics --user
code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

storage:
  # storage account and container where the ImageNet tar balls are contained
  output:
    storage_account_name: zeliuwestus2
    container_name: aml
    mount_dir: /aml_output
  data:
    storage_account_name: zeliuwestus2
    container_name: aml
    mount_dir: /aml_data
  model:
    storage_account_name: zeliuwestus2
    container_name: aml
    mount_dir: /aml_model

jobs:
 - name: mi200_exp
   sku: 64G16-MI200-IB-xGMI
   priority: High
   execution_mode: basic
   azml_int: True
   process_count_per_node: 1
   command:
    - bash train_mi200.sh
   submit_args:
      container_args:
         shm_size: 2048g
      env:
       {
         SHARED_MEMORY_PERCENT: 1.0,
       }