model:
  base_learning_rate: 1.5e-06
  max_epochs: 100
  lr_steps: [75, 95]
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    first_stage_key: image
    cond_stage_key: class_label
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 512
        n_layer: 12
        n_head: 12
        n_embd: 768
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: results/2020-09-23T17-56-33_imagenet_vqgan/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.DummyLoss
    cond_stage_config:
      target: taming.modules.util.Labelator
      params:
        n_classes: 1000
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 16
    train:
      target: taming.data.imagenet.ImageNetTrain
      params:
        # root_path: "/data/home/zhez/data/imagenet/"
        root_path: "./aml_data/imagenet1000/"
        folder_name: "train"
        config:
          size: 256
    validation:
      target: taming.data.imagenet.ImageNetValidation
      params:
        # root_path: "/data/home/zhez/data/imagenet/"
        root_path: "./aml_data/imagenet1000/"
        folder_name: "val"
        config:
          size: 256
image_logger:
  target: main.ImageLogger
  params:
    batch_frequency: 1000
    max_images: 4
    clamp: True
lightning:
  trainer:
    gpus: 0,1,2,3